import * as fs from 'fs/promises';
import * as path from 'path';
import * as globby from 'globby';
import debug from './debug';
import { camelize } from './utils';

/**
 * 生成 ts 文件，用于代码补全
 * @param paths service 文件扫描路径
 * @param tsFile ts 文件保存路径
 * @param patterns 匹配规则
 */
export async function findServicesToTyping(paths: string[], tsFile: string, patterns?: string) {
  const typingsPath = path.dirname(tsFile);
  const headerCode = [
    '// zenweb service typing',
    '// This file is automatically generated',
    '// Please do not modify',
    `// date: ${new Date().toLocaleString()}`,
    `// user: ${process.env.USER || process.env.USERNAME || 'unknown'}@${process.env.COMPUTERNAME || 'unknown'}`,
    '',
  ];
  const declareCode = [];
  for (const directory of paths) {
    headerCode.push(`// directory: ${directory}`);
    for (const fullpath of await globby(patterns || '**/*.{ts,js}', { cwd: directory, absolute: true })) {
      const cls = require(fullpath.slice(0, -3));
      if (cls.default) {
        const filename = fullpath.slice(directory.length + 1);
        const propertyName = camelize(filename);
        const className = propertyName[0].toUpperCase() + propertyName.slice(1);
        let importFilename = path.relative(typingsPath, fullpath.slice(0, -3)).replace(/\\/g, '/');
        if (!importFilename.startsWith('.')) {
          importFilename = `./${importFilename}`;
        }
        headerCode.push(`import ${className} from '${importFilename}';`);
        declareCode.push(`    ${propertyName}: ${className};`);
      }
    }
  }

  const code = [...headerCode];
  code.push('');
  code.push(`declare module '@zenweb/service' {`);
  code.push(`  interface Services {`);
  code.push(...declareCode);
  code.push(`  }`);
  code.push(`}`);
  code.push('');

  debug(`write types file: ${tsFile}`);

  await fs.mkdir(typingsPath, { recursive: true });
  await fs.writeFile(tsFile, code.join('\n'));
}
